// ─────────────────────────────────────────────────────────────────────────────
// INVESTMENT CATALOG — Static definitions for all investment categories
// Admin can override price / change24h / enabled via platform_settings
// key: investment_catalog_overrides  (JSON object keyed by instrument id)
// ─────────────────────────────────────────────────────────────────────────────

export const INVESTMENT_CATEGORIES = [
  // ── Original 9 ────────────────────────────────────────────────────────────
  { id: "stocks",       label: "Stocks",          icon: "TrendingUp",  color: "blue",    bg: "bg-blue-500/10",    text: "text-blue-500",    border: "border-blue-500/30",    description: "Shares of publicly listed companies from global markets" },
  { id: "etfs",         label: "ETFs",             icon: "BarChart3",   color: "violet",  bg: "bg-violet-500/10",  text: "text-violet-500",  border: "border-violet-500/30",  description: "Exchange-traded funds tracking global indices & sectors" },
  { id: "bonds",        label: "Bonds",            icon: "Shield",      color: "emerald", bg: "bg-emerald-500/10", text: "text-emerald-500", border: "border-emerald-500/30", description: "Government & sovereign fixed-income securities worldwide" },
  { id: "fixed_income", label: "Fixed Income",     icon: "Percent",     color: "cyan",    bg: "bg-cyan-500/10",    text: "text-cyan-500",    border: "border-cyan-500/30",    description: "Corporate bonds, T-bills & structured credit products" },
  { id: "commodities",  label: "Commodities",      icon: "Flame",       color: "orange",  bg: "bg-orange-500/10",  text: "text-orange-500",  border: "border-orange-500/30",  description: "Raw materials traded on global exchanges" },
  { id: "futures",      label: "Futures",          icon: "Clock",       color: "yellow",  bg: "bg-yellow-500/10",  text: "text-yellow-500",  border: "border-yellow-500/30",  description: "Derivative contracts for future delivery across markets" },
  { id: "options",      label: "Options",          icon: "Layers",      color: "pink",    bg: "bg-pink-500/10",    text: "text-pink-500",    border: "border-pink-500/30",    description: "Rights to buy or sell assets at a strike price" },
  { id: "metals",       label: "Metals",           icon: "Gem",         color: "amber",   bg: "bg-amber-500/10",   text: "text-amber-500",   border: "border-amber-500/30",   description: "Precious & industrial metals spot markets" },
  { id: "nfts",         label: "NFTs",             icon: "Palette",     color: "purple",  bg: "bg-purple-500/10",  text: "text-purple-500",  border: "border-purple-500/30",  description: "Curated non-fungible token collections" },
  // ── New 3 ─────────────────────────────────────────────────────────────────
  { id: "reits",        label: "REITs",            icon: "Building2",   color: "teal",    bg: "bg-teal-500/10",    text: "text-teal-500",    border: "border-teal-500/30",    description: "Real estate investment trusts — income-generating property exposure" },
  { id: "private_eq",   label: "Private Equity",   icon: "Briefcase",   color: "indigo",  bg: "bg-indigo-500/10",  text: "text-indigo-500",  border: "border-indigo-500/30",  description: "Alternative asset managers and private capital platforms" },
  { id: "alternatives", label: "Alternatives",     icon: "Sparkles",    color: "rose",    bg: "bg-rose-500/10",    text: "text-rose-500",    border: "border-rose-500/30",    description: "Crowdfunding, art, collectibles & alternative income assets" },
];

// ─────────────────────────────────────────────────────────────────────────────
// INSTRUMENT CATALOG
// region: ISO country code or "GLOBAL". Drives the region filter.
// currency: native trading currency (prices stored in USD regardless)
// ─────────────────────────────────────────────────────────────────────────────
export const INVESTMENT_INSTRUMENTS = [

  // ─── STOCKS — US ──────────────────────────────────────────────────────────
  { id: "AAPL",  region: "US", category: "stocks", name: "Apple Inc.",            symbol: "AAPL",  icon: "🍎", price: 187.15, change24h: 1.23,  changePct24h: 0.66,  marketCap: "$2.86T", volume24h: "$52.3B", exchange: "NASDAQ", minInvestment: 1,  currency: "USD", enabled: true, description: "Apple designs, manufactures and markets smartphones, personal computers, tablets, wearables and accessories. Known for iPhone, Mac, iPad and services ecosystem." },
  { id: "MSFT",  region: "US", category: "stocks", name: "Microsoft Corp.",       symbol: "MSFT",  icon: "⊞",  price: 378.80, change24h: 2.40,  changePct24h: 0.64,  marketCap: "$2.82T", volume24h: "$24.1B", exchange: "NASDAQ", minInvestment: 1,  currency: "USD", enabled: true, description: "Microsoft develops, licenses and supports software, services, devices and solutions worldwide. Leader in cloud computing through Azure." },
  { id: "TSLA",  region: "US", category: "stocks", name: "Tesla Inc.",            symbol: "TSLA",  icon: "⚡",  price: 175.34, change24h: -3.21, changePct24h: -1.80, marketCap: "$557B",  volume24h: "$18.7B", exchange: "NASDAQ", minInvestment: 1,  currency: "USD", enabled: true, description: "Tesla designs and manufactures electric vehicles, energy storage systems, solar panels and related products. Leading EV manufacturer globally." },
  { id: "GOOGL", region: "US", category: "stocks", name: "Alphabet Inc.",         symbol: "GOOGL", icon: "G",  price: 160.55, change24h: 0.88,  changePct24h: 0.55,  marketCap: "$2.01T", volume24h: "$21.5B", exchange: "NASDAQ", minInvestment: 1,  currency: "USD", enabled: true, description: "Alphabet operates the world's largest search engine, YouTube, Android and Google Cloud. Core of the global digital advertising industry." },
  { id: "AMZN",  region: "US", category: "stocks", name: "Amazon.com Inc.",       symbol: "AMZN",  icon: "A",  price: 183.30, change24h: 1.55,  changePct24h: 0.85,  marketCap: "$1.91T", volume24h: "$35.8B", exchange: "NASDAQ", minInvestment: 1,  currency: "USD", enabled: true, description: "Amazon operates e-commerce, cloud computing (AWS), digital streaming and artificial intelligence businesses worldwide." },
  { id: "NVDA",  region: "US", category: "stocks", name: "NVIDIA Corp.",          symbol: "NVDA",  icon: "N",  price: 875.40, change24h: 12.80, changePct24h: 1.48,  marketCap: "$2.16T", volume24h: "$44.2B", exchange: "NASDAQ", minInvestment: 1,  currency: "USD", enabled: true, description: "NVIDIA designs graphics processing units for gaming, professional visualization, data center and automotive markets. Dominates AI chip market." },
  { id: "META",  region: "US", category: "stocks", name: "Meta Platforms Inc.",   symbol: "META",  icon: "M",  price: 485.20, change24h: 3.10,  changePct24h: 0.64,  marketCap: "$1.24T", volume24h: "$16.3B", exchange: "NASDAQ", minInvestment: 1,  currency: "USD", enabled: true, description: "Meta operates Facebook, Instagram, WhatsApp and Messenger, reaching billions of users. Investing heavily in the metaverse and AI." },
  { id: "BRKB",  region: "US", category: "stocks", name: "Berkshire Hathaway B",  symbol: "BRK-B", icon: "B",  price: 410.65, change24h: 0.55,  changePct24h: 0.13,  marketCap: "$908B",  volume24h: "$3.2B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "Berkshire Hathaway is a conglomerate holding company led by Warren Buffett, with investments across insurance, utilities, railways and consumer brands." },
  { id: "NFLX",  region: "US", category: "stocks", name: "Netflix Inc.",          symbol: "NFLX",  icon: "N",  price: 628.10, change24h: -2.30, changePct24h: -0.36, marketCap: "$274B",  volume24h: "$4.8B",  exchange: "NASDAQ", minInvestment: 1,  currency: "USD", enabled: true, description: "Netflix is the world's leading streaming entertainment service with 260M+ paid subscribers across 190 countries." },
  { id: "JPMC",  region: "US", category: "stocks", name: "JPMorgan Chase & Co.",  symbol: "JPM",   icon: "J",  price: 198.45, change24h: 0.95,  changePct24h: 0.48,  marketCap: "$571B",  volume24h: "$8.1B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "JPMorgan Chase is the largest US bank by assets, offering investment banking, commercial banking, financial services and asset management." },

  // ─── STOCKS — UK ──────────────────────────────────────────────────────────
  { id: "HSBA",  region: "GB", category: "stocks", name: "HSBC Holdings",         symbol: "HSBA",  icon: "H",  price: 55.90,  change24h: 0.42,  changePct24h: 0.76,  marketCap: "$145B",  volume24h: "$1.8B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "HSBC is one of the world's largest banking and financial services organisations, with operations in 64 countries. Headquartered in London, core markets in Asia." },
  { id: "SHEL",  region: "GB", category: "stocks", name: "Shell plc",             symbol: "SHEL",  icon: "S",  price: 67.30,  change24h: 0.95,  changePct24h: 1.43,  marketCap: "$223B",  volume24h: "$1.5B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "Shell is a global energy company active in more than 70 countries. Operates in oil, gas, LNG, biofuels, hydrogen and electricity businesses." },
  { id: "BP",    region: "GB", category: "stocks", name: "BP plc",                symbol: "BP",    icon: "B",  price: 33.40,  change24h: 0.28,  changePct24h: 0.84,  marketCap: "$94B",   volume24h: "$0.8B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "BP is a major integrated energy company transitioning towards lower carbon energy. Operations span oil, gas, wind, solar and EV charging." },
  { id: "AZN",   region: "GB", category: "stocks", name: "AstraZeneca",           symbol: "AZN",   icon: "A",  price: 80.20,  change24h: -0.35, changePct24h: -0.44, marketCap: "$253B",  volume24h: "$0.9B",  exchange: "NASDAQ", minInvestment: 1,  currency: "USD", enabled: true, description: "AstraZeneca is a global biopharmaceutical company focused on oncology, cardiovascular, renal, metabolic and respiratory diseases." },
  { id: "ULVR",  region: "GB", category: "stocks", name: "Unilever plc",          symbol: "UL",    icon: "U",  price: 52.10,  change24h: 0.18,  changePct24h: 0.35,  marketCap: "$131B",  volume24h: "$0.5B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "Unilever is a global consumer goods company with brands across beauty, personal care, home care, food and refreshment." },

  // ─── STOCKS — Europe ──────────────────────────────────────────────────────
  { id: "ASML",  region: "EU", category: "stocks", name: "ASML Holding",          symbol: "ASML",  icon: "A",  price: 895.40, change24h: 8.60,  changePct24h: 0.97,  marketCap: "$352B",  volume24h: "$1.2B",  exchange: "NASDAQ", minInvestment: 1,  currency: "USD", enabled: true, description: "ASML is the world's sole producer of EUV lithography machines used in advanced semiconductor manufacturing. Critical enabler for AI chip production." },
  { id: "SAP",   region: "EU", category: "stocks", name: "SAP SE",                symbol: "SAP",   icon: "S",  price: 185.30, change24h: 2.15,  changePct24h: 1.17,  marketCap: "$228B",  volume24h: "$0.7B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "SAP is the world's largest enterprise software company, providing ERP, CRM, analytics and cloud solutions to 400,000+ customers globally." },
  { id: "LVMUY", region: "EU", category: "stocks", name: "LVMH Moët Hennessy",    symbol: "LVMUY", icon: "L",  price: 73.40,  change24h: 0.48,  changePct24h: 0.66,  marketCap: "$365B",  volume24h: "$0.4B",  exchange: "OTC",    minInvestment: 1,  currency: "USD", enabled: true, description: "LVMH is the world's largest luxury goods conglomerate, owning 75+ prestigious brands including Louis Vuitton, Dior, Moët & Chandon and Hennessy." },
  { id: "SIEGY", region: "EU", category: "stocks", name: "Siemens AG",            symbol: "SIEGY", icon: "S",  price: 87.20,  change24h: 0.90,  changePct24h: 1.04,  marketCap: "$94B",   volume24h: "$0.3B",  exchange: "OTC",    minInvestment: 1,  currency: "USD", enabled: true, description: "Siemens is a global technology powerhouse operating in automation, digitalization, electrification and healthcare equipment." },
  { id: "NESNY", region: "EU", category: "stocks", name: "Nestlé S.A.",           symbol: "NSRGY", icon: "N",  price: 84.50,  change24h: -0.25, changePct24h: -0.30, marketCap: "$237B",  volume24h: "$0.4B",  exchange: "OTC",    minInvestment: 1,  currency: "USD", enabled: true, description: "Nestlé is the world's largest food and beverage company, with brands like Nescafé, KitKat, Maggi, Perrier, Purina and Milo sold in 188 countries." },
  { id: "TTEF",  region: "EU", category: "stocks", name: "TotalEnergies SE",      symbol: "TTE",   icon: "T",  price: 62.10,  change24h: 0.65,  changePct24h: 1.06,  marketCap: "$157B",  volume24h: "$0.6B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "TotalEnergies is a French integrated energy company producing and marketing oil, natural gas, renewables and electricity in 130+ countries." },

  // ─── STOCKS — Japan ───────────────────────────────────────────────────────
  { id: "TM",    region: "JP", category: "stocks", name: "Toyota Motor Corp.",    symbol: "TM",    icon: "T",  price: 188.50, change24h: 1.80,  changePct24h: 0.96,  marketCap: "$261B",  volume24h: "$0.5B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "Toyota is the world's largest automobile manufacturer, pioneering hybrid technology with Prius and expanding rapidly into hydrogen fuel cell vehicles." },
  { id: "SONY",  region: "JP", category: "stocks", name: "Sony Group Corp.",      symbol: "SONY",  icon: "S",  price: 82.40,  change24h: 0.95,  changePct24h: 1.17,  marketCap: "$104B",  volume24h: "$0.4B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "Sony is a global technology and entertainment company active in gaming (PlayStation), music, movies, semiconductors and consumer electronics." },
  { id: "HMC",   region: "JP", category: "stocks", name: "Honda Motor Co.",       symbol: "HMC",   icon: "H",  price: 29.30,  change24h: 0.22,  changePct24h: 0.76,  marketCap: "$48B",   volume24h: "$0.2B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "Honda is a leading Japanese manufacturer of automobiles, motorcycles, and power equipment with a growing focus on hydrogen fuel cell vehicles." },
  { id: "SFTBY", region: "JP", category: "stocks", name: "SoftBank Group",        symbol: "SFTBY", icon: "S",  price: 23.80,  change24h: -0.40, changePct24h: -1.65, marketCap: "$43B",   volume24h: "$0.2B",  exchange: "OTC",    minInvestment: 1,  currency: "USD", enabled: true, description: "SoftBank Group is a Japanese multinational conglomerate and investment company focused on technology. Home to the Vision Fund — the world's largest tech VC fund." },

  // ─── STOCKS — China / HK ──────────────────────────────────────────────────
  { id: "BABA",  region: "CN", category: "stocks", name: "Alibaba Group",         symbol: "BABA",  icon: "A",  price: 78.40,  change24h: 1.20,  changePct24h: 1.55,  marketCap: "$184B",  volume24h: "$2.1B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "Alibaba is China's largest e-commerce and cloud computing company, operating Taobao, Tmall, Aliyun and Ant Group. Major player in global trade." },
  { id: "TCEHY", region: "CN", category: "stocks", name: "Tencent Holdings",      symbol: "TCEHY", icon: "T",  price: 44.80,  change24h: 0.55,  changePct24h: 1.24,  marketCap: "$409B",  volume24h: "$0.9B",  exchange: "OTC",    minInvestment: 1,  currency: "USD", enabled: true, description: "Tencent is China's biggest technology company — operating WeChat, QQ, gaming (Honor of Kings), music, payments and cloud services." },
  { id: "JD",    region: "CN", category: "stocks", name: "JD.com Inc.",           symbol: "JD",    icon: "J",  price: 28.90,  change24h: 0.40,  changePct24h: 1.40,  marketCap: "$45B",   volume24h: "$0.6B",  exchange: "NASDAQ", minInvestment: 1,  currency: "USD", enabled: true, description: "JD.com is China's largest direct-sales online retailer, known for its same-day delivery infrastructure and quality-assurance model." },
  { id: "PDD",   region: "CN", category: "stocks", name: "PDD Holdings",          symbol: "PDD",   icon: "P",  price: 105.30, change24h: 2.80,  changePct24h: 2.73,  marketCap: "$147B",  volume24h: "$1.4B",  exchange: "NASDAQ", minInvestment: 1,  currency: "USD", enabled: true, description: "PDD Holdings operates Pinduoduo and Temu — China's fastest-growing e-commerce platform and a rapidly expanding international marketplace." },

  // ─── STOCKS — India ───────────────────────────────────────────────────────
  { id: "INFY",  region: "IN", category: "stocks", name: "Infosys Ltd.",          symbol: "INFY",  icon: "I",  price: 18.50,  change24h: 0.15,  changePct24h: 0.82,  marketCap: "$77B",   volume24h: "$0.3B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "Infosys is a global IT services and consulting company with 300,000+ employees. Leading provider of digital, cloud and AI transformation services." },
  { id: "HDB",   region: "IN", category: "stocks", name: "HDFC Bank",             symbol: "HDB",   icon: "H",  price: 64.20,  change24h: 0.35,  changePct24h: 0.55,  marketCap: "$176B",  volume24h: "$0.4B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "HDFC Bank is India's largest private sector bank by assets, known for strong asset quality, digital banking and retail operations across 8,300+ branches." },
  { id: "WIT",   region: "IN", category: "stocks", name: "Wipro Ltd.",            symbol: "WIT",   icon: "W",  price: 5.80,   change24h: 0.04,  changePct24h: 0.69,  marketCap: "$30B",   volume24h: "$0.1B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "Wipro is a leading Indian IT services company offering cloud, digital, engineering and consulting services to enterprises globally." },

  // ─── STOCKS — Canada ──────────────────────────────────────────────────────
  { id: "SHOP",  region: "CA", category: "stocks", name: "Shopify Inc.",          symbol: "SHOP",  icon: "S",  price: 70.40,  change24h: 1.05,  changePct24h: 1.51,  marketCap: "$88B",   volume24h: "$0.9B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "Shopify is a leading global commerce platform helping businesses of all sizes sell online and in-person. Powers 2M+ merchants in 175 countries." },
  { id: "RY",    region: "CA", category: "stocks", name: "Royal Bank of Canada",  symbol: "RY",    icon: "R",  price: 121.30, change24h: 0.65,  changePct24h: 0.54,  marketCap: "$172B",  volume24h: "$0.4B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "Royal Bank of Canada is Canada's largest bank by market cap — providing personal, commercial, corporate and investment banking services globally." },
  { id: "BNS",   region: "CA", category: "stocks", name: "Bank of Nova Scotia",   symbol: "BNS",   icon: "B",  price: 43.20,  change24h: 0.30,  changePct24h: 0.70,  marketCap: "$52B",   volume24h: "$0.2B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "Scotiabank is Canada's third-largest bank, with a significant focus on Latin America and the Caribbean as a key growth market alongside domestic operations." },

  // ─── STOCKS — Australia ───────────────────────────────────────────────────
  { id: "BHP",   region: "AU", category: "stocks", name: "BHP Group",             symbol: "BHP",   icon: "B",  price: 46.80,  change24h: 0.55,  changePct24h: 1.19,  marketCap: "$236B",  volume24h: "$0.8B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "BHP is the world's largest diversified mining company, producing iron ore, copper, coal and nickel — critical inputs for steel, EVs and energy transition." },
  { id: "RIO",   region: "AU", category: "stocks", name: "Rio Tinto",             symbol: "RIO",   icon: "R",  price: 65.20,  change24h: 0.70,  changePct24h: 1.08,  marketCap: "$105B",  volume24h: "$0.5B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "Rio Tinto is a major diversified miner focused on iron ore, aluminium, copper and lithium. Strong position in green metals for the energy transition." },

  // ─── STOCKS — South Korea ─────────────────────────────────────────────────
  { id: "SSNLF", region: "KR", category: "stocks", name: "Samsung Electronics",   symbol: "SSNLF", icon: "S",  price: 55.20,  change24h: 0.80,  changePct24h: 1.47,  marketCap: "$329B",  volume24h: "$0.5B",  exchange: "OTC",    minInvestment: 1,  currency: "USD", enabled: true, description: "Samsung Electronics is the world's largest chipmaker and consumer electronics manufacturer, producing memory, displays, smartphones and home appliances." },

  // ─── STOCKS — Brazil ──────────────────────────────────────────────────────
  { id: "VALE",  region: "BR", category: "stocks", name: "Vale S.A.",             symbol: "VALE",  icon: "V",  price: 11.80,  change24h: 0.18,  changePct24h: 1.55,  marketCap: "$54B",   volume24h: "$0.7B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "Vale is the world's largest producer of iron ore and nickel, headquartered in Brazil. Key beneficiary of global infrastructure and EV demand." },
  { id: "ITUB",  region: "BR", category: "stocks", name: "Itaú Unibanco",         symbol: "ITUB",  icon: "I",  price: 7.20,   change24h: 0.08,  changePct24h: 1.12,  marketCap: "$71B",   volume24h: "$0.3B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "Itaú Unibanco is Latin America's largest financial institution by market cap, serving 60M+ clients across banking, insurance and asset management." },

  // ─── STOCKS — Singapore ───────────────────────────────────────────────────
  { id: "DBSGY", region: "SG", category: "stocks", name: "DBS Group Holdings",    symbol: "DBSGY", icon: "D",  price: 35.20,  change24h: 0.45,  changePct24h: 1.30,  marketCap: "$91B",   volume24h: "$0.4B",  exchange: "OTC",    minInvestment: 1,  currency: "USD", enabled: true, description: "DBS is Southeast Asia's largest bank by assets, consistently ranked among the world's best digital banks. Strong franchise across Singapore, Hong Kong, China and India." },
  { id: "SNGPF", region: "SG", category: "stocks", name: "Singtel",               symbol: "SNGPF", icon: "S",  price: 2.05,   change24h: 0.02,  changePct24h: 0.98,  marketCap: "$33B",   volume24h: "$0.1B",  exchange: "OTC",    minInvestment: 1,  currency: "USD", enabled: true, description: "Singapore Telecommunications (Singtel) is Asia's leading communications group, with operations across Singapore, Australia (Optus), and digital investments across Asia." },
  { id: "SE",    region: "SG", category: "stocks", name: "Sea Limited",           symbol: "SE",    icon: "🌊", price: 48.90,  change24h: 0.85,  changePct24h: 1.77,  marketCap: "$28B",   volume24h: "$0.5B",  exchange: "NYSE",   minInvestment: 1,  currency: "USD", enabled: true, description: "Sea Limited operates Garena (gaming), Shopee (e-commerce) and SeaMoney (fintech) across Southeast Asia. One of the region's largest tech companies by market cap." },

  // ─── ETFs — US ────────────────────────────────────────────────────────────
  { id: "SPY",    region: "US",     category: "etfs", name: "SPDR S&P 500 ETF",       symbol: "SPY",   icon: "S",  price: 521.30, change24h: 2.10,  changePct24h: 0.40,  marketCap: "$508B",  volume24h: "$28.4B", exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Tracks the S&P 500 index, providing exposure to 500 of the largest US companies. One of the world's most traded ETFs." },
  { id: "QQQ",    region: "US",     category: "etfs", name: "Invesco QQQ Trust",       symbol: "QQQ",   icon: "Q",  price: 439.55, change24h: 3.20,  changePct24h: 0.73,  marketCap: "$245B",  volume24h: "$19.8B", exchange: "NASDAQ",minInvestment: 1, currency: "USD", enabled: true, description: "Tracks the NASDAQ-100 index, heavily weighted toward large-cap technology stocks. Popular for growth-oriented investors." },
  { id: "VTI",    region: "US",     category: "etfs", name: "Vanguard Total Market",   symbol: "VTI",   icon: "V",  price: 238.70, change24h: 1.05,  changePct24h: 0.44,  marketCap: "$380B",  volume24h: "$5.6B",  exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Provides exposure to the entire US stock market, covering large-, mid-, small- and micro-cap stocks. Ultra-low expense ratio." },
  { id: "VOO",    region: "US",     category: "etfs", name: "Vanguard S&P 500 ETF",    symbol: "VOO",   icon: "V",  price: 479.20, change24h: 1.95,  changePct24h: 0.41,  marketCap: "$436B",  volume24h: "$6.3B",  exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Vanguard's version of the S&P 500 ETF, known for its extremely low 0.03% expense ratio. Ideal for long-term investors." },
  { id: "ARKK",   region: "US",     category: "etfs", name: "ARK Innovation ETF",      symbol: "ARKK",  icon: "K",  price: 48.35,  change24h: -0.75, changePct24h: -1.53, marketCap: "$6.8B",  volume24h: "$1.2B",  exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Actively managed ETF focused on disruptive innovation including genomics, AI, fintech, autonomous tech and next-gen internet." },
  { id: "IWM",    region: "US",     category: "etfs", name: "iShares Russell 2000",    symbol: "IWM",   icon: "I",  price: 201.15, change24h: 0.60,  changePct24h: 0.30,  marketCap: "$62B",   volume24h: "$4.7B",  exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Tracks the Russell 2000 index of small-cap US stocks, offering exposure to the smaller end of the US equity market." },
  { id: "XLE",    region: "US",     category: "etfs", name: "Energy Select Sector",    symbol: "XLE",   icon: "E",  price: 89.45,  change24h: 1.20,  changePct24h: 1.36,  marketCap: "$38B",   volume24h: "$1.8B",  exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Tracks energy companies in the S&P 500, including oil, gas, consumable fuels and energy equipment & services companies." },
  { id: "GLDETF", region: "US",     category: "etfs", name: "SPDR Gold Shares ETF",    symbol: "GLD",   icon: "G",  price: 214.60, change24h: 0.80,  changePct24h: 0.37,  marketCap: "$64B",   volume24h: "$2.1B",  exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Backed by physical gold stored in vaults. Provides gold exposure without the complexity of storing physical metal." },
  { id: "SLVETF", region: "US",     category: "etfs", name: "iShares Silver Trust",    symbol: "SLV",   icon: "S",  price: 23.15,  change24h: 0.35,  changePct24h: 1.54,  marketCap: "$9.2B",  volume24h: "$0.8B",  exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Backed by physical silver, offering exposure to silver spot price performance through a simple ETF structure." },

  // ─── ETFs — International ─────────────────────────────────────────────────
  { id: "EWJ",    region: "JP",     category: "etfs", name: "iShares MSCI Japan",      symbol: "EWJ",   icon: "🇯🇵", price: 68.20,  change24h: 0.55,  changePct24h: 0.81,  marketCap: "$18B",   volume24h: "$0.5B",  exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Tracks the MSCI Japan Index — exposure to large and mid-cap Japanese equities including Toyota, Sony, Mitsubishi UFJ and Fast Retailing." },
  { id: "EWG",    region: "EU",     category: "etfs", name: "iShares MSCI Germany",    symbol: "EWG",   icon: "🇩🇪", price: 31.45,  change24h: 0.28,  changePct24h: 0.90,  marketCap: "$4.3B",  volume24h: "$0.2B",  exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Tracks the MSCI Germany Index — exposure to SAP, Siemens, Allianz, BASF, BMW and other DAX-listed companies." },
  { id: "EWU",    region: "GB",     category: "etfs", name: "iShares MSCI UK",         symbol: "EWU",   icon: "🇬🇧", price: 37.80,  change24h: 0.18,  changePct24h: 0.48,  marketCap: "$2.8B",  volume24h: "$0.1B",  exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Tracks the MSCI United Kingdom Index — exposure to AstraZeneca, HSBC, Shell, Unilever and other FTSE 100 giants." },
  { id: "FXI",    region: "CN",     category: "etfs", name: "iShares China Large-Cap", symbol: "FXI",   icon: "🇨🇳", price: 28.95,  change24h: 0.42,  changePct24h: 1.47,  marketCap: "$6.1B",  volume24h: "$0.4B",  exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Tracks the FTSE China 50 Index — top 50 Chinese companies listed on Hong Kong Stock Exchange including Tencent, Alibaba, Meituan and ICBC." },
  { id: "EWZ",    region: "BR",     category: "etfs", name: "iShares MSCI Brazil",     symbol: "EWZ",   icon: "🇧🇷", price: 32.10,  change24h: 0.35,  changePct24h: 1.10,  marketCap: "$5.8B",  volume24h: "$0.3B",  exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Tracks the MSCI Brazil 25/50 Index — exposure to Petrobras, Vale, Itaú Unibanco and other Brazilian blue chips." },
  { id: "VEA",    region: "GLOBAL", category: "etfs", name: "Vanguard Dev. Markets",   symbol: "VEA",   icon: "V",  price: 51.20,  change24h: 0.28,  changePct24h: 0.55,  marketCap: "$132B",  volume24h: "$1.8B",  exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Tracks the FTSE Developed All Cap ex US Index — broad exposure to developed markets in Europe, Asia-Pacific and Canada. 3,900+ holdings." },
  { id: "VXUS",   region: "GLOBAL", category: "etfs", name: "Vanguard Total Intl",     symbol: "VXUS",  icon: "V",  price: 62.40,  change24h: 0.22,  changePct24h: 0.35,  marketCap: "$66B",   volume24h: "$0.9B",  exchange: "NASDAQ",minInvestment: 1, currency: "USD", enabled: true, description: "Tracks total international stock market (developed + emerging) excluding the US. 8,000+ holdings for maximum global diversification." },
  { id: "ACWI",   region: "GLOBAL", category: "etfs", name: "iShares MSCI ACWI",       symbol: "ACWI",  icon: "A",  price: 105.80, change24h: 0.48,  changePct24h: 0.46,  marketCap: "$22B",   volume24h: "$0.4B",  exchange: "NASDAQ",minInvestment: 1, currency: "USD", enabled: true, description: "Tracks the MSCI All Country World Index — the broadest global ETF, covering large and mid-cap stocks across 23 developed and 24 emerging markets." },
  { id: "VGK",    region: "EU",     category: "etfs", name: "Vanguard FTSE Europe",    symbol: "VGK",   icon: "V",  price: 68.90,  change24h: 0.30,  changePct24h: 0.44,  marketCap: "$17B",   volume24h: "$0.3B",  exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Tracks the FTSE Developed Europe All Cap Index — broad European equity exposure across UK, France, Germany, Switzerland, Netherlands and more." },
  { id: "EEM",    region: "GLOBAL", category: "etfs", name: "iShares MSCI Emerging",   symbol: "EEM",   icon: "E",  price: 42.80,  change24h: 0.25,  changePct24h: 0.59,  marketCap: "$22B",   volume24h: "$1.5B",  exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Provides exposure to large and mid-cap equities from emerging market countries including China, India, Brazil, Taiwan and South Korea." },
  { id: "INDA",   region: "IN",     category: "etfs", name: "iShares MSCI India",      symbol: "INDA",  icon: "🇮🇳", price: 56.70,  change24h: 0.65,  changePct24h: 1.16,  marketCap: "$9.4B",  volume24h: "$0.3B",  exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Tracks the MSCI India Index — exposure to Reliance, Infosys, HDFC Bank, TCS and other leading Indian equities as the economy grows rapidly." },
  { id: "EWC",    region: "CA",     category: "etfs", name: "iShares MSCI Canada",     symbol: "EWC",   icon: "🇨🇦", price: 42.10,  change24h: 0.38,  changePct24h: 0.91,  marketCap: "$2.8B",  volume24h: "$0.1B",  exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Tracks the MSCI Canada Custom Capped Index — exposure to Royal Bank, Shopify, TD Bank, Enbridge and other Canadian market leaders." },
  { id: "EWA",    region: "AU",     category: "etfs", name: "iShares MSCI Australia",  symbol: "EWA",   icon: "🇦🇺", price: 25.30,  change24h: 0.20,  changePct24h: 0.80,  marketCap: "$1.8B",  volume24h: "$0.1B",  exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Tracks the MSCI Australia Index — exposure to BHP, CBA, CSL, ANZ, NAB and other S&P/ASX 200 constituents." },
  { id: "EWS",    region: "SG",     category: "etfs", name: "iShares MSCI Singapore",  symbol: "EWS",   icon: "🇸🇬", price: 22.40,  change24h: 0.18,  changePct24h: 0.81,  marketCap: "$0.9B",  volume24h: "$0.1B",  exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Tracks the MSCI Singapore 25/50 Index — exposure to DBS, OCBC, UOB, Singapore Exchange, Singtel and other STI constituents. Gateway to Southeast Asia." },

  // ─── BONDS — US ───────────────────────────────────────────────────────────
  { id: "US10Y",  region: "US", category: "bonds", name: "US 10-Year Treasury",   symbol: "US10Y",  icon: "$",  price: 98.20,  change24h: 0.05,  changePct24h: 0.05,  marketCap: "—",     volume24h: "—",     exchange: "US Treasury",     minInvestment: 100, currency: "USD", enabled: true, yield: "4.52%", maturity: "10 Years", rating: "AAA", description: "Benchmark US government bond maturing in 10 years. Considered virtually risk-free and widely used as a global safe-haven asset." },
  { id: "US30Y",  region: "US", category: "bonds", name: "US 30-Year Treasury",   symbol: "US30Y",  icon: "$",  price: 93.40,  change24h: -0.10, changePct24h: -0.11, marketCap: "—",     volume24h: "—",     exchange: "US Treasury",     minInvestment: 100, currency: "USD", enabled: true, yield: "4.75%", maturity: "30 Years", rating: "AAA", description: "Long-duration US government bond. Offers higher yield than the 10Y with greater sensitivity to interest rate changes." },
  { id: "US2Y",   region: "US", category: "bonds", name: "US 2-Year Treasury",    symbol: "US2Y",   icon: "$",  price: 99.85,  change24h: 0.02,  changePct24h: 0.02,  marketCap: "—",     volume24h: "—",     exchange: "US Treasury",     minInvestment: 100, currency: "USD", enabled: true, yield: "4.90%", maturity: "2 Years",  rating: "AAA", description: "Short-term US government note. Highly liquid and sensitive to Fed policy decisions. Used as a proxy for near-term rate expectations." },

  // ─── BONDS — International ────────────────────────────────────────────────
  { id: "UKGILT", region: "GB", category: "bonds", name: "UK 10Y Gilt",           symbol: "UKT10",  icon: "£",  price: 96.10,  change24h: -0.08, changePct24h: -0.08, marketCap: "—",     volume24h: "—",     exchange: "UK DMO",          minInvestment: 100, currency: "GBP", enabled: true, yield: "4.28%", maturity: "10 Years", rating: "AA",  description: "UK government bond issued by the UK Debt Management Office. Very low risk and denominated in British pounds. Sensitive to Bank of England policy." },
  { id: "BUND",   region: "EU", category: "bonds", name: "German 10Y Bund",       symbol: "DBR10",  icon: "€",  price: 97.65,  change24h: 0.03,  changePct24h: 0.03,  marketCap: "—",     volume24h: "—",     exchange: "Deutsche Finance", minInvestment: 100, currency: "EUR", enabled: true, yield: "2.50%", maturity: "10 Years", rating: "AAA", description: "German government bond — the euro area benchmark bond. Considered the safest EUR-denominated sovereign bond. Used as the European risk-free rate." },
  { id: "JGB10Y", region: "JP", category: "bonds", name: "Japan 10Y Gov Bond",    symbol: "JGB10Y", icon: "¥",  price: 98.40,  change24h: -0.05, changePct24h: -0.05, marketCap: "—",     volume24h: "—",     exchange: "Japan MOF",       minInvestment: 100, currency: "JPY", enabled: true, yield: "0.87%", maturity: "10 Years", rating: "A+",  description: "Japanese government bond — world's largest bond market by sovereign issuance. BoJ controls yields through yield curve control policy." },
  { id: "OAT10Y", region: "EU", category: "bonds", name: "France 10Y OAT",        symbol: "OAT10Y", icon: "€",  price: 95.80,  change24h: 0.02,  changePct24h: 0.02,  marketCap: "—",     volume24h: "—",     exchange: "Agence France",   minInvestment: 100, currency: "EUR", enabled: true, yield: "3.15%", maturity: "10 Years", rating: "AA-", description: "French government bond. Obligation Assimilable du Trésor — core Euro-area sovereign with slight spread over German Bund reflecting French fiscal position." },
  { id: "BTP10Y", region: "EU", category: "bonds", name: "Italy 10Y BTP",         symbol: "BTP10Y", icon: "€",  price: 91.20,  change24h: -0.12, changePct24h: -0.13, marketCap: "—",     volume24h: "—",     exchange: "Italy MEF",       minInvestment: 100, currency: "EUR", enabled: true, yield: "4.10%", maturity: "10 Years", rating: "BBB", description: "Italian government bond — highest yielding major Euro-area sovereign. Spread over Bund reflects Italy's high debt-to-GDP ratio and political risk premium." },
  { id: "CANGOV", region: "CA", category: "bonds", name: "Canada 10Y Gov Bond",   symbol: "CANGOV", icon: "C$", price: 97.10,  change24h: 0.04,  changePct24h: 0.04,  marketCap: "—",     volume24h: "—",     exchange: "Govt of Canada",  minInvestment: 100, currency: "CAD", enabled: true, yield: "3.68%", maturity: "10 Years", rating: "AAA", description: "Canadian federal government bond. Rated AAA with a small yield spread over US Treasuries. Influenced by Bank of Canada monetary policy." },
  { id: "AUSGOV", region: "AU", category: "bonds", name: "Australia 10Y Bond",    symbol: "AUSGOV", icon: "A$", price: 96.50,  change24h: 0.06,  changePct24h: 0.06,  marketCap: "—",     volume24h: "—",     exchange: "AOFM",            minInvestment: 100, currency: "AUD", enabled: true, yield: "4.35%", maturity: "10 Years", rating: "AAA", description: "Australian Commonwealth Government Security. Higher yielding than US or German equivalents. Backed by Australia's resource-rich AAA-rated economy." },

  // ─── FIXED INCOME ─────────────────────────────────────────────────────────
  { id: "TBILL3M", region: "US", category: "fixed_income", name: "US T-Bill 3-Month",      symbol: "TBILL3M", icon: "$",  price: 99.92,  change24h: 0.01,  changePct24h: 0.01,  marketCap: "—",     volume24h: "—",     exchange: "US Treasury", minInvestment: 100,  currency: "USD", enabled: true, yield: "5.28%", maturity: "3 Months", rating: "AAA", description: "Short-term US government obligation with near-zero default risk. Popular cash management instrument for institutional investors." },
  { id: "IGBOND",  region: "US", category: "fixed_income", name: "IG Corporate Bond",       symbol: "IGBOND",  icon: "IG", price: 97.30,  change24h: 0.10,  changePct24h: 0.10,  marketCap: "—",     volume24h: "—",     exchange: "OTC",         minInvestment: 500,  currency: "USD", enabled: true, yield: "5.45%", maturity: "5 Years",  rating: "BBB", description: "Investment-grade corporate bond basket tracking debt from companies with strong credit ratings. Offers yield premium over Treasuries." },
  { id: "HYBOND",  region: "US", category: "fixed_income", name: "High-Yield Corp Bond",    symbol: "HYBOND",  icon: "HY", price: 95.10,  change24h: -0.20, changePct24h: -0.21, marketCap: "—",     volume24h: "—",     exchange: "OTC",         minInvestment: 500,  currency: "USD", enabled: true, yield: "7.80%", maturity: "5 Years",  rating: "BB",  description: "Below-investment-grade corporate bonds offering higher yields in exchange for greater credit risk. Also called junk bonds." },
  { id: "MUNI",    region: "US", category: "fixed_income", name: "Municipal Bond",          symbol: "MUNI",    icon: "M",  price: 98.50,  change24h: 0.05,  changePct24h: 0.05,  marketCap: "—",     volume24h: "—",     exchange: "OTC",         minInvestment: 500,  currency: "USD", enabled: true, yield: "3.80%", maturity: "10 Years", rating: "AA",  description: "Debt securities issued by US states and municipalities. Interest income is typically exempt from federal income tax." },
  { id: "AGMBS",   region: "US", category: "fixed_income", name: "Agency MBS",              symbol: "AGMBS",   icon: "AG", price: 96.40,  change24h: 0.08,  changePct24h: 0.08,  marketCap: "—",     volume24h: "—",     exchange: "OTC",         minInvestment: 1000, currency: "USD", enabled: true, yield: "5.65%", maturity: "30 Years", rating: "AAA", description: "Mortgage-backed securities guaranteed by Fannie Mae, Freddie Mac or Ginnie Mae. Offer higher yield than Treasuries with implicit government backing." },

  // ─── COMMODITIES ──────────────────────────────────────────────────────────
  { id: "WTICRUDE", region: "GLOBAL", category: "commodities", name: "WTI Crude Oil",    symbol: "WTI",     icon: "🛢",  price: 82.45,  change24h: 1.10,  changePct24h: 1.35,  marketCap: "—",     volume24h: "$22B",   exchange: "NYMEX",  minInvestment: 10,  currency: "USD", enabled: true,  unit: "per barrel", description: "West Texas Intermediate — the US benchmark crude oil. Price affected by OPEC decisions, US inventory levels and global demand trends." },
  { id: "NATGAS",   region: "GLOBAL", category: "commodities", name: "Natural Gas",      symbol: "NG",      icon: "🔥",  price: 1.95,   change24h: -0.05, changePct24h: -2.50, marketCap: "—",     volume24h: "$4.5B",  exchange: "NYMEX",  minInvestment: 10,  currency: "USD", enabled: true,  unit: "per MMBtu",  description: "Henry Hub natural gas — the North American benchmark for natural gas. Highly seasonal commodity driven by weather and LNG exports." },
  { id: "WHEAT",    region: "GLOBAL", category: "commodities", name: "Wheat",            symbol: "ZW",      icon: "🌾",  price: 545.25, change24h: 4.75,  changePct24h: 0.88,  marketCap: "—",     volume24h: "$1.2B",  exchange: "CBOT",   minInvestment: 10,  currency: "USD", enabled: true,  unit: "per bushel", description: "CBOT wheat futures — a global agricultural benchmark affected by weather, geopolitics and global food supply dynamics." },
  { id: "CORN",     region: "GLOBAL", category: "commodities", name: "Corn",             symbol: "ZC",      icon: "🌽",  price: 435.50, change24h: 2.25,  changePct24h: 0.52,  marketCap: "—",     volume24h: "$1.8B",  exchange: "CBOT",   minInvestment: 10,  currency: "USD", enabled: true,  unit: "per bushel", description: "CBOT corn futures. Primary uses include food, animal feed and ethanol production. Sensitive to US planting intentions and South American harvests." },
  { id: "COFFEE",   region: "GLOBAL", category: "commodities", name: "Coffee",           symbol: "KC",      icon: "☕",  price: 190.35, change24h: -1.20, changePct24h: -0.63, marketCap: "—",     volume24h: "$0.8B",  exchange: "ICE",    minInvestment: 10,  currency: "USD", enabled: true,  unit: "per lb",     description: "ICE Arabica coffee futures — affected by weather in Brazil and Colombia, currency fluctuations and global demand trends." },
  { id: "COTTON",   region: "GLOBAL", category: "commodities", name: "Cotton",           symbol: "CT",      icon: "🌿",  price: 79.85,  change24h: 0.55,  changePct24h: 0.69,  marketCap: "—",     volume24h: "$0.5B",  exchange: "ICE",    minInvestment: 10,  currency: "USD", enabled: true,  unit: "per lb",     description: "ICE cotton futures — a key input for textile industry. Price influenced by weather, global supply and trade policy." },
  { id: "SOYBEANS", region: "GLOBAL", category: "commodities", name: "Soybeans",         symbol: "ZS",      icon: "🫘",  price: 1132.5, change24h: 6.25,  changePct24h: 0.55,  marketCap: "—",     volume24h: "$2.2B",  exchange: "CBOT",   minInvestment: 10,  currency: "USD", enabled: true,  unit: "per bushel", description: "CBOT soybean futures. Used for crushing into soybean oil and meal for animal feed. Affected by South American weather and Chinese demand." },

  // ─── FUTURES ──────────────────────────────────────────────────────────────
  { id: "ES",       region: "US",     category: "futures", name: "S&P 500 E-Mini",      symbol: "ES",      icon: "ES", price: 5215.50, change24h: 18.25, changePct24h: 0.35,  marketCap: "—",     volume24h: "$280B",  exchange: "CME",    minInvestment: 50, currency: "USD", enabled: true,  expiryDate: "Jun 2025", contractSize: "$50×index", description: "The most liquid equity index futures contract in the world. Used for hedging S&P 500 exposure and speculative trading." },
  { id: "NQ",       region: "US",     category: "futures", name: "NASDAQ E-Mini",       symbol: "NQ",      icon: "NQ", price: 18440.25,change24h: 95.50, changePct24h: 0.52,  marketCap: "—",     volume24h: "$180B",  exchange: "CME",    minInvestment: 50, currency: "USD", enabled: true,  expiryDate: "Jun 2025", contractSize: "$20×index", description: "E-mini futures tracking the NASDAQ-100 index. Popular with tech sector traders and hedge funds." },
  { id: "CL",       region: "GLOBAL", category: "futures", name: "Crude Oil Futures",   symbol: "CL",      icon: "CL", price: 82.80,   change24h: 1.15,  changePct24h: 1.41,  marketCap: "—",     volume24h: "$45B",   exchange: "NYMEX",  minInvestment: 50, currency: "USD", enabled: true,  expiryDate: "May 2025", contractSize: "1,000 bbl", description: "WTI crude oil futures — the benchmark for US oil pricing. Highly liquid with massive daily volumes from traders, hedgers and producers." },
  { id: "GCF",      region: "GLOBAL", category: "futures", name: "Gold Futures",        symbol: "GC",      icon: "GC", price: 2315.80, change24h: 12.40, changePct24h: 0.54,  marketCap: "—",     volume24h: "$35B",   exchange: "COMEX",  minInvestment: 50, currency: "USD", enabled: true,  expiryDate: "Jun 2025", contractSize: "100 troy oz", description: "COMEX gold futures — used for hedging inflation risk and geopolitical uncertainty. One of the oldest futures markets globally." },
  { id: "SIF",      region: "GLOBAL", category: "futures", name: "Silver Futures",      symbol: "SI",      icon: "SI", price: 27.45,   change24h: 0.38,  changePct24h: 1.40,  marketCap: "—",     volume24h: "$8B",    exchange: "COMEX",  minInvestment: 50, currency: "USD", enabled: true,  expiryDate: "May 2025", contractSize: "5,000 troy oz", description: "COMEX silver futures — more volatile than gold with significant industrial demand. Used for speculation and industrial hedging." },
  { id: "NGF",      region: "GLOBAL", category: "futures", name: "Natural Gas Futures",  symbol: "NGF",     icon: "NG", price: 1.98,    change24h: -0.04, changePct24h: -1.98, marketCap: "—",     volume24h: "$6B",    exchange: "NYMEX",  minInvestment: 50, currency: "USD", enabled: true,  expiryDate: "May 2025", contractSize: "10,000 MMBtu", description: "Henry Hub natural gas futures. Among the most volatile commodity futures due to weather seasonality and rapidly shifting supply/demand." },

  // ─── OPTIONS ──────────────────────────────────────────────────────────────
  { id: "AAPL-CALL-200", region: "US", category: "options", name: "AAPL Call $200",   symbol: "AAPL $200C", icon: "C", price: 4.80,  change24h: 0.35,  changePct24h: 7.87,  marketCap: "—", volume24h: "—", exchange: "CBOE", minInvestment: 10, currency: "USD", enabled: true, optionType: "Call", strike: "$200", expiry: "Jun 20, 2025", underlying: "AAPL", description: "Call option on Apple stock with $200 strike. Profitable if AAPL rises above $200 before expiry. Leverage amplifies both gains and losses." },
  { id: "SPY-PUT-500",   region: "US", category: "options", name: "SPY Put $500",     symbol: "SPY $500P",  icon: "P", price: 8.25,  change24h: -0.50, changePct24h: -5.71, marketCap: "—", volume24h: "—", exchange: "CBOE", minInvestment: 10, currency: "USD", enabled: true, optionType: "Put",  strike: "$500", expiry: "Jun 20, 2025", underlying: "SPY",  description: "Put option on SPY ETF with $500 strike. Provides downside protection or speculative short exposure to S&P 500." },
  { id: "TSLA-CALL-200", region: "US", category: "options", name: "TSLA Call $200",   symbol: "TSLA $200C", icon: "C", price: 6.15,  change24h: -0.80, changePct24h: -11.5, marketCap: "—", volume24h: "—", exchange: "CBOE", minInvestment: 10, currency: "USD", enabled: true, optionType: "Call", strike: "$200", expiry: "Jun 20, 2025", underlying: "TSLA", description: "Call option on Tesla stock. High implied volatility makes Tesla options expensive but potentially very rewarding if the stock moves sharply." },
  { id: "NVDA-CALL-900", region: "US", category: "options", name: "NVDA Call $900",   symbol: "NVDA $900C", icon: "C", price: 22.50, change24h: 3.10,  changePct24h: 15.97, marketCap: "—", volume24h: "—", exchange: "CBOE", minInvestment: 10, currency: "USD", enabled: true, optionType: "Call", strike: "$900", expiry: "Jun 20, 2025", underlying: "NVDA", description: "Call option on NVIDIA stock. AI demand narrative makes NVDA one of the most actively traded options contracts in the market." },
  { id: "QQQ-PUT-420",   region: "US", category: "options", name: "QQQ Put $420",     symbol: "QQQ $420P",  icon: "P", price: 5.40,  change24h: 0.20,  changePct24h: 3.85,  marketCap: "—", volume24h: "—", exchange: "CBOE", minInvestment: 10, currency: "USD", enabled: true, optionType: "Put",  strike: "$420", expiry: "Jun 20, 2025", underlying: "QQQ",  description: "Put option on QQQ ETF providing bearish exposure to NASDAQ-100 technology stocks. Popular hedge for tech-heavy portfolios." },

  // ─── METALS ───────────────────────────────────────────────────────────────
  { id: "XAUUSD", region: "GLOBAL", category: "metals", name: "Gold Spot",       symbol: "XAU/USD", icon: "Au", price: 2318.50, change24h: 14.20, changePct24h: 0.62,  marketCap: "~$14T",  volume24h: "$220B", exchange: "OTC Spot", minInvestment: 10, currency: "USD", enabled: true, unit: "per troy oz", description: "Gold spot price — the world's premier safe-haven asset. Inversely correlated with USD and real interest rates. Central bank favorite reserve." },
  { id: "XAGUSD", region: "GLOBAL", category: "metals", name: "Silver Spot",     symbol: "XAG/USD", icon: "Ag", price: 27.55,   change24h: 0.42,  changePct24h: 1.55,  marketCap: "~$1.7T", volume24h: "$15B",  exchange: "OTC Spot", minInvestment: 10, currency: "USD", enabled: true, unit: "per troy oz", description: "Silver spot price — dual role as precious metal and industrial commodity (solar panels, electronics). More volatile than gold." },
  { id: "XPTUSD", region: "GLOBAL", category: "metals", name: "Platinum Spot",   symbol: "XPT/USD", icon: "Pt", price: 985.30,  change24h: 8.15,  changePct24h: 0.84,  marketCap: "~$230B", volume24h: "$1.2B", exchange: "OTC Spot", minInvestment: 10, currency: "USD", enabled: true, unit: "per troy oz", description: "Platinum spot price — rarer than gold with significant auto-catalyst demand. Strong South African supply concentration." },
  { id: "XPDUSD", region: "GLOBAL", category: "metals", name: "Palladium Spot",  symbol: "XPD/USD", icon: "Pd", price: 1045.80, change24h: -5.60, changePct24h: -0.53, marketCap: "~$80B",  volume24h: "$0.5B", exchange: "OTC Spot", minInvestment: 10, currency: "USD", enabled: true, unit: "per troy oz", description: "Palladium — used primarily in catalytic converters for petrol engines. One of the rarest metals, most supply from Russia and South Africa." },
  { id: "XCUUSD", region: "GLOBAL", category: "metals", name: "Copper Spot",     symbol: "XCU/USD", icon: "Cu", price: 4.28,    change24h: 0.06,  changePct24h: 1.42,  marketCap: "~$800B", volume24h: "$12B",  exchange: "LME",      minInvestment: 10, currency: "USD", enabled: true, unit: "per lb",      description: "Copper — the 'PhD in economics' metal. Critical for electrification, EV batteries and renewable energy infrastructure. A key indicator of global growth." },

  // ─── NFTs ─────────────────────────────────────────────────────────────────
  { id: "PUNKS",   region: "GLOBAL", category: "nfts", name: "CryptoPunks",         symbol: "PUNKS",  icon: "👾", price: 48500,  change24h: 850,   changePct24h: 1.79,  marketCap: "$1.5B", volume24h: "$3.2M", exchange: "Ethereum", minInvestment: 100, currency: "USD", enabled: true, blockchain: "Ethereum", supply: "10,000", floorPrice: "48.5 ETH", description: "CryptoPunks — one of the first NFT projects on Ethereum. 10,000 algorithmically generated pixel art characters. Iconic status as OG NFT collection." },
  { id: "BAYC",    region: "GLOBAL", category: "nfts", name: "Bored Ape Yacht Club",symbol: "BAYC",   icon: "🦍", price: 32500,  change24h: -500,  changePct24h: -1.52, marketCap: "$1.2B", volume24h: "$1.8M", exchange: "Ethereum", minInvestment: 100, currency: "USD", enabled: true, blockchain: "Ethereum", supply: "10,000", floorPrice: "32.5 ETH", description: "Bored Ape Yacht Club — collection of 10,000 unique Bored Ape NFTs. Holder membership grants access to exclusive events and commercial rights." },
  { id: "AZUKI",   region: "GLOBAL", category: "nfts", name: "Azuki",               symbol: "AZUKI",  icon: "🎴", price: 8900,   change24h: 120,   changePct24h: 1.37,  marketCap: "$220M", volume24h: "$0.9M", exchange: "Ethereum", minInvestment: 100, currency: "USD", enabled: true, blockchain: "Ethereum", supply: "10,000", floorPrice: "8.9 ETH",  description: "Azuki is a brand for the metaverse — built by anime and streetwear enthusiasts. High-quality art with a strong community and brand partnerships." },
  { id: "DOODLES", region: "GLOBAL", category: "nfts", name: "Doodles",             symbol: "DOODLE", icon: "🌈", price: 4200,   change24h: 85,    changePct24h: 2.07,  marketCap: "$105M", volume24h: "$0.5M", exchange: "Ethereum", minInvestment: 100, currency: "USD", enabled: true, blockchain: "Ethereum", supply: "10,000", floorPrice: "4.2 ETH",  description: "Doodles is a community-driven NFT collection featuring colorful characters. Known for active community governance and events." },
  { id: "CLONEX",  region: "GLOBAL", category: "nfts", name: "Clone X",             symbol: "CLONEX", icon: "🤖", price: 3800,   change24h: -120,  changePct24h: -3.07, marketCap: "$95M",  volume24h: "$0.6M", exchange: "Ethereum", minInvestment: 100, currency: "USD", enabled: true, blockchain: "Ethereum", supply: "19,000", floorPrice: "3.8 ETH",  description: "Clone X by RTFKT x Takashi Murakami — 3D avatar collection designed for the metaverse. Each clone can be used in games and virtual worlds." },

  // ─── REITs ────────────────────────────────────────────────────────────────
  { id: "VNQ",     region: "US", category: "reits", name: "Vanguard Real Estate ETF", symbol: "VNQ",  icon: "🏢", price: 88.50,  change24h: 0.42,  changePct24h: 0.48,  marketCap: "$30B",   volume24h: "$0.8B", exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, yield: "4.20%", description: "Tracks the MSCI US IMI Real Estate 25/50 Index — the broadest US REIT ETF. Exposure to 160+ real estate companies across all property types." },
  { id: "O",       region: "US", category: "reits", name: "Realty Income Corp",      symbol: "O",    icon: "O",  price: 55.20,  change24h: 0.28,  changePct24h: 0.51,  marketCap: "$34B",   volume24h: "$0.4B", exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, yield: "5.80%", description: "The Monthly Dividend Company — Realty Income pays dividends every month. Portfolio of 13,250+ properties leased to 1,500+ tenants globally." },
  { id: "SPG",     region: "US", category: "reits", name: "Simon Property Group",    symbol: "SPG",  icon: "S",  price: 148.30, change24h: 0.95,  changePct24h: 0.64,  marketCap: "$45B",   volume24h: "$0.6B", exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, yield: "5.40%", description: "Simon Property is the largest mall REIT in the US, owning premium outlet centers and regional malls that generate consistent foot traffic and rental income." },
  { id: "PLD",     region: "US", category: "reits", name: "Prologis Inc.",           symbol: "PLD",  icon: "P",  price: 115.40, change24h: 0.60,  changePct24h: 0.52,  marketCap: "$89B",   volume24h: "$0.8B", exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, yield: "3.10%", description: "Prologis is the world's largest logistics REIT, owning 1.2B+ sq ft of e-commerce warehouses and distribution centers in 19 countries." },
  { id: "EQIX",    region: "US", category: "reits", name: "Equinix Inc.",            symbol: "EQIX", icon: "E",  price: 842.30, change24h: 5.20,  changePct24h: 0.62,  marketCap: "$78B",   volume24h: "$0.5B", exchange: "NASDAQ",minInvestment: 1, currency: "USD", enabled: true, yield: "2.10%", description: "Equinix is the world's largest data center REIT with 260+ data centers across 71 metros in 33 countries. Powers the internet's core interconnection." },
  { id: "AMT",     region: "US", category: "reits", name: "American Tower Corp",     symbol: "AMT",  icon: "A",  price: 188.50, change24h: 1.10,  changePct24h: 0.59,  marketCap: "$87B",   volume24h: "$0.6B", exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, yield: "3.40%", description: "American Tower is the world's largest cell tower REIT with 222,000+ communication towers across 25 countries. Benefits from 5G rollout globally." },
  { id: "PSA",     region: "US", category: "reits", name: "Public Storage",          symbol: "PSA",  icon: "P",  price: 304.20, change24h: 1.80,  changePct24h: 0.60,  marketCap: "$53B",   volume24h: "$0.4B", exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, yield: "4.00%", description: "Public Storage is the largest self-storage REIT in the US with 3,000+ facilities. Self-storage is a recession-resilient, high-margin real estate sector." },
  { id: "DLR",     region: "US", category: "reits", name: "Digital Realty Trust",    symbol: "DLR",  icon: "D",  price: 145.80, change24h: 0.90,  changePct24h: 0.62,  marketCap: "$43B",   volume24h: "$0.4B", exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, yield: "2.80%", description: "Digital Realty is a leading data center REIT serving 5,000+ customers including IBM, Oracle, LinkedIn and AT&T across 50 metros worldwide." },
  { id: "WELL",    region: "US", category: "reits", name: "Welltower Inc.",          symbol: "WELL", icon: "W",  price: 109.70, change24h: 0.48,  changePct24h: 0.44,  marketCap: "$56B",   volume24h: "$0.5B", exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, yield: "2.30%", description: "Welltower is a healthcare REIT owning senior housing, post-acute care facilities and outpatient medical buildings — benefiting from aging demographics." },
  { id: "CICT",    region: "SG", category: "reits", name: "CapitaLand Integ Comm Tr",symbol: "CICT", icon: "🏬", price: 1.85,   change24h: 0.02,  changePct24h: 1.09,  marketCap: "$12B",   volume24h: "$0.1B", exchange: "SGX",    minInvestment: 1, currency: "USD", enabled: true, yield: "5.50%", description: "CapitaLand Integrated Commercial Trust is Singapore's largest REIT, owning a portfolio of 21 properties including malls and office towers across Singapore and Germany." },

  // ─── PRIVATE EQUITY ───────────────────────────────────────────────────────
  { id: "BX",      region: "US", category: "private_eq", name: "Blackstone Inc.",       symbol: "BX",   icon: "B",  price: 136.80, change24h: 2.10,  changePct24h: 1.56,  marketCap: "$168B",  volume24h: "$1.5B", exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Blackstone is the world's largest alternative asset manager with $1T+ AUM across private equity, real estate, credit and hedge fund strategies." },
  { id: "KKR",     region: "US", category: "private_eq", name: "KKR & Co.",             symbol: "KKR",  icon: "K",  price: 105.40, change24h: 1.60,  changePct24h: 1.54,  marketCap: "$93B",   volume24h: "$0.9B", exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "KKR is a leading global investment firm managing PE, infrastructure, real estate and credit with $553B+ AUM. Pioneer of the leveraged buyout strategy." },
  { id: "APO",     region: "US", category: "private_eq", name: "Apollo Global Mgmt",    symbol: "APO",  icon: "A",  price: 118.20, change24h: 1.80,  changePct24h: 1.55,  marketCap: "$71B",   volume24h: "$0.7B", exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Apollo is a high-growth alternative asset manager focused on credit, equity and real assets with $671B AUM. Strong track record in distressed investing." },
  { id: "CG",      region: "US", category: "private_eq", name: "Carlyle Group",         symbol: "CG",   icon: "C",  price: 48.70,  change24h: 0.65,  changePct24h: 1.35,  marketCap: "$17B",   volume24h: "$0.2B", exchange: "NASDAQ",minInvestment: 1, currency: "USD", enabled: true, description: "Carlyle is a global investment firm with $426B AUM across private equity, real assets and global credit. Known for defence and aerospace sector expertise." },
  { id: "BAM",     region: "CA", category: "private_eq", name: "Brookfield Asset Mgmt", symbol: "BAM",  icon: "B",  price: 47.20,  change24h: 0.38,  changePct24h: 0.81,  marketCap: "$76B",   volume24h: "$0.4B", exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Brookfield Asset Management is a Canadian alternative asset manager with $920B+ AUM across real estate, infrastructure, renewable power and private equity." },
  { id: "ARES",    region: "US", category: "private_eq", name: "Ares Management Corp",  symbol: "ARES", icon: "A",  price: 148.40, change24h: 2.20,  changePct24h: 1.51,  marketCap: "$51B",   volume24h: "$0.3B", exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Ares Management is an alternative asset manager specialising in credit-first strategies with $428B AUM. One of the world's largest direct lending platforms." },
  { id: "BN",      region: "CA", category: "private_eq", name: "Brookfield Corp",       symbol: "BN",   icon: "B",  price: 52.30,  change24h: 0.45,  changePct24h: 0.87,  marketCap: "$83B",   volume24h: "$0.3B", exchange: "NYSE",   minInvestment: 1, currency: "USD", enabled: true, description: "Brookfield Corporation is the parent of Brookfield AM — a diversified operator of real assets including renewable energy, infrastructure, real estate and insurance." },

  // ─── ALTERNATIVES / CROWDFUNDING ──────────────────────────────────────────
  { id: "CF_REALESTATE", region: "US",     category: "alternatives", name: "Fundrise Real Estate",  symbol: "CFRE",    icon: "🏠", price: 10.00,  change24h: 0.05,  changePct24h: 0.50,  marketCap: "—", volume24h: "—", exchange: "Fundrise",  minInvestment: 10,  currency: "USD", enabled: true, yield: "8.40%", description: "Fundrise is the leading real estate crowdfunding platform. Invest in diversified portfolios of private real estate projects — commercial, residential and industrial — with as little as $10." },
  { id: "CF_STARTUPS",   region: "US",     category: "alternatives", name: "Republic Startup Fund",  symbol: "CFST",    icon: "🚀", price: 50.00,  change24h: 0.00,  changePct24h: 0.00,  marketCap: "—", volume24h: "—", exchange: "Republic",  minInvestment: 50,  currency: "USD", enabled: true, description: "Invest in early-stage startups through equity crowdfunding. Diversified exposure to pre-IPO technology, biotech and consumer companies. SEC Reg CF compliant." },
  { id: "CF_ART",        region: "US",     category: "alternatives", name: "Masterworks Art Fund",   symbol: "CFART",   icon: "🎨", price: 20.00,  change24h: 0.10,  changePct24h: 0.50,  marketCap: "—", volume24h: "—", exchange: "Masterworks",minInvestment: 20,  currency: "USD", enabled: true, yield: "14.6%", description: "Masterworks securitises blue-chip contemporary art by Banksy, Basquiat, KAWS and Koons. Historical art index outperformed S&P 500 by 250% over 27 years." },
  { id: "CF_COLLECTIBLES",region: "US",    category: "alternatives", name: "Rally Collectibles Fund",symbol: "CFRLY",   icon: "🏆", price: 25.00,  change24h: 0.08,  changePct24h: 0.32,  marketCap: "—", volume24h: "—", exchange: "Rally",     minInvestment: 25,  currency: "USD", enabled: true, description: "Invest in fractional shares of rare collectibles — sports cards, vintage cars, watches, sneakers and memorabilia. Rally provides SEC-qualified asset-backed shares." },
  { id: "CF_INFRA",      region: "GLOBAL", category: "alternatives", name: "Yieldstreet Alt Income", symbol: "CFYLD",   icon: "⚡", price: 15.00,  change24h: 0.07,  changePct24h: 0.47,  marketCap: "—", volume24h: "—", exchange: "Yieldstreet",minInvestment: 15,  currency: "USD", enabled: true, yield: "9.50%", description: "Yieldstreet provides access to alternative income investments in marine finance, legal finance, infrastructure and real estate — historically uncorrelated to markets." },
  { id: "CF_FARMLAND",   region: "US",     category: "alternatives", name: "AcreTrader Farmland",    symbol: "CFFRM",   icon: "🌱", price: 30.00,  change24h: 0.12,  changePct24h: 0.40,  marketCap: "—", volume24h: "—", exchange: "AcreTrader",  minInvestment: 30,  currency: "USD", enabled: true, yield: "7.00%", description: "AcreTrader lets investors own shares in high-quality US farmland — the world's scarcest asset. Farmland has returned ~11% annually with very low volatility." },
  { id: "CF_LENDING",    region: "GLOBAL", category: "alternatives", name: "P2P Lending Portfolio",  symbol: "CFP2P",   icon: "🤝", price: 5.00,   change24h: 0.02,  changePct24h: 0.40,  marketCap: "—", volume24h: "—", exchange: "Platform",    minInvestment: 5,   currency: "USD", enabled: true, yield: "10.5%", description: "Diversified exposure to consumer and SME loans across global peer-to-peer lending platforms. Monthly interest income paid to investors. Risk-graded portfolios." },
];

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────
export const getCategoryById = (id) =>
  INVESTMENT_CATEGORIES.find((c) => c.id === id) ?? null;

export const getInstrumentById = (id) =>
  INVESTMENT_INSTRUMENTS.find((i) => i.id === id) ?? null;

export const getInstrumentsByCategory = (categoryId) =>
  INVESTMENT_INSTRUMENTS.filter((i) => i.category === categoryId);

export const getInstrumentsByRegion = (regionCode) =>
  regionCode === "all"
    ? INVESTMENT_INSTRUMENTS
    : INVESTMENT_INSTRUMENTS.filter((i) => i.region === regionCode);

// Region lookup for display
export const REGIONS = [
  { id: "all",    label: "All Regions",   flag: "🌐" },
  { id: "US",     label: "United States", flag: "🇺🇸" },
  { id: "GB",     label: "UK",            flag: "🇬🇧" },
  { id: "EU",     label: "Europe",        flag: "🇪🇺" },
  { id: "JP",     label: "Japan",         flag: "🇯🇵" },
  { id: "CN",     label: "China",         flag: "🇨🇳" },
  { id: "IN",     label: "India",         flag: "🇮🇳" },
  { id: "CA",     label: "Canada",        flag: "🇨🇦" },
  { id: "AU",     label: "Australia",     flag: "🇦🇺" },
  { id: "KR",     label: "South Korea",   flag: "🇰🇷" },
  { id: "BR",     label: "Brazil",        flag: "🇧🇷" },
  { id: "SG",     label: "Singapore",     flag: "🇸🇬" },
  { id: "GLOBAL", label: "Global",        flag: "🌍" },
];

export const getRegionById = (id) => REGIONS.find((r) => r.id === id) ?? REGIONS[0];

// Merge static catalog with admin overrides from platform_settings
// overrides shape: { [instrumentId]: { price?, change24h?, changePct24h?, enabled?, ... } }
export const mergeWithOverrides = (overrides = {}) => {
  const base = [...INVESTMENT_INSTRUMENTS];

  // Apply per-instrument overrides
  const merged = base.map((inst) => {
    const ov = overrides[inst.id];
    if (!ov) return inst;
    return { ...inst, ...ov };
  });

  // Append any admin-added custom instruments
  const custom = overrides.__custom ?? [];
  return [...merged, ...custom];
};
