// ─────────────────────────────────────────────────────────────────────────────
// INVESTMENT CATALOG — Static definitions for all investment categories
// Admin can override price / change24h / enabled via platform_settings
// key: investment_catalog_overrides  (JSON object keyed by instrument id)
// ─────────────────────────────────────────────────────────────────────────────

export const INVESTMENT_CATEGORIES = [
  { id: "stocks",       label: "Stocks",         icon: "TrendingUp",  color: "blue",    bg: "bg-blue-500/10",    text: "text-blue-500",    border: "border-blue-500/30",    description: "Shares of publicly listed companies" },
  { id: "etfs",         label: "ETFs",            icon: "BarChart3",   color: "violet",  bg: "bg-violet-500/10",  text: "text-violet-500",  border: "border-violet-500/30",  description: "Exchange-traded funds tracking indices & sectors" },
  { id: "bonds",        label: "Bonds",           icon: "Shield",      color: "emerald", bg: "bg-emerald-500/10", text: "text-emerald-500", border: "border-emerald-500/30", description: "Government & sovereign fixed-income securities" },
  { id: "fixed_income", label: "Fixed Income",    icon: "Percent",     color: "cyan",    bg: "bg-cyan-500/10",    text: "text-cyan-500",    border: "border-cyan-500/30",    description: "Corporate bonds, T-bills & structured products" },
  { id: "commodities",  label: "Commodities",     icon: "Flame",       color: "orange",  bg: "bg-orange-500/10",  text: "text-orange-500",  border: "border-orange-500/30",  description: "Raw materials traded on global exchanges" },
  { id: "futures",      label: "Futures",         icon: "Clock",       color: "yellow",  bg: "bg-yellow-500/10",  text: "text-yellow-500",  border: "border-yellow-500/30",  description: "Derivative contracts for future delivery" },
  { id: "options",      label: "Options",         icon: "Layers",      color: "pink",    bg: "bg-pink-500/10",    text: "text-pink-500",    border: "border-pink-500/30",    description: "Rights to buy or sell assets at a strike price" },
  { id: "metals",       label: "Metals",          icon: "Gem",         color: "amber",   bg: "bg-amber-500/10",   text: "text-amber-500",   border: "border-amber-500/30",   description: "Precious & industrial metals spot markets" },
  { id: "nfts",         label: "NFTs",            icon: "Palette",     color: "purple",  bg: "bg-purple-500/10",  text: "text-purple-500",  border: "border-purple-500/30",  description: "Curated non-fungible token collections" },
];

// ─────────────────────────────────────────────────────────────────────────────
// INSTRUMENT CATALOG
// icon: 1-3 char text badge (matches CRYPTO_ASSETS / FIAT_CURRENCIES pattern)
// ─────────────────────────────────────────────────────────────────────────────
export const INVESTMENT_INSTRUMENTS = [

  // ─── STOCKS ───────────────────────────────────────────────────────────────
  { id: "AAPL",  category: "stocks", name: "Apple Inc.",            symbol: "AAPL",  icon: "🍎", price: 187.15, change24h: 1.23,  changePct24h: 0.66,  marketCap: "$2.86T", volume24h: "$52.3B", exchange: "NASDAQ",  minInvestment: 1,   currency: "USD", enabled: true,  description: "Apple designs, manufactures and markets smartphones, personal computers, tablets, wearables and accessories. Known for iPhone, Mac, iPad and services ecosystem." },
  { id: "MSFT",  category: "stocks", name: "Microsoft Corp.",       symbol: "MSFT",  icon: "⊞",  price: 378.80, change24h: 2.40,  changePct24h: 0.64,  marketCap: "$2.82T", volume24h: "$24.1B", exchange: "NASDAQ",  minInvestment: 1,   currency: "USD", enabled: true,  description: "Microsoft develops, licenses and supports software, services, devices and solutions worldwide. Leader in cloud computing through Azure." },
  { id: "TSLA",  category: "stocks", name: "Tesla Inc.",            symbol: "TSLA",  icon: "⚡",  price: 175.34, change24h: -3.21, changePct24h: -1.80, marketCap: "$557B",  volume24h: "$18.7B", exchange: "NASDAQ",  minInvestment: 1,   currency: "USD", enabled: true,  description: "Tesla designs and manufactures electric vehicles, energy storage systems, solar panels and related products. Leading EV manufacturer globally." },
  { id: "GOOGL", category: "stocks", name: "Alphabet Inc.",         symbol: "GOOGL", icon: "G",  price: 160.55, change24h: 0.88,  changePct24h: 0.55,  marketCap: "$2.01T", volume24h: "$21.5B", exchange: "NASDAQ",  minInvestment: 1,   currency: "USD", enabled: true,  description: "Alphabet is a holding company with Google at its core — operating the world's largest search engine, YouTube, Android and cloud services." },
  { id: "AMZN",  category: "stocks", name: "Amazon.com Inc.",       symbol: "AMZN",  icon: "A",  price: 183.30, change24h: 1.55,  changePct24h: 0.85,  marketCap: "$1.91T", volume24h: "$35.8B", exchange: "NASDAQ",  minInvestment: 1,   currency: "USD", enabled: true,  description: "Amazon operates e-commerce, cloud computing (AWS), digital streaming and artificial intelligence businesses worldwide." },
  { id: "NVDA",  category: "stocks", name: "NVIDIA Corp.",          symbol: "NVDA",  icon: "N",  price: 875.40, change24h: 12.80, changePct24h: 1.48,  marketCap: "$2.16T", volume24h: "$44.2B", exchange: "NASDAQ",  minInvestment: 1,   currency: "USD", enabled: true,  description: "NVIDIA designs graphics processing units for gaming, professional visualization, data center and automotive markets. Dominates AI chip market." },
  { id: "META",  category: "stocks", name: "Meta Platforms Inc.",   symbol: "META",  icon: "M",  price: 485.20, change24h: 3.10,  changePct24h: 0.64,  marketCap: "$1.24T", volume24h: "$16.3B", exchange: "NASDAQ",  minInvestment: 1,   currency: "USD", enabled: true,  description: "Meta operates Facebook, Instagram, WhatsApp and Messenger, reaching billions of users. Investing heavily in the metaverse and AI." },
  { id: "BRKB",  category: "stocks", name: "Berkshire Hathaway B",  symbol: "BRK-B", icon: "B",  price: 410.65, change24h: 0.55,  changePct24h: 0.13,  marketCap: "$908B",  volume24h: "$3.2B",  exchange: "NYSE",    minInvestment: 1,   currency: "USD", enabled: true,  description: "Berkshire Hathaway is a conglomerate holding company led by Warren Buffett, with investments across insurance, utilities, railways and consumer brands." },
  { id: "NFLX",  category: "stocks", name: "Netflix Inc.",          symbol: "NFLX",  icon: "N",  price: 628.10, change24h: -2.30, changePct24h: -0.36, marketCap: "$274B",  volume24h: "$4.8B",  exchange: "NASDAQ",  minInvestment: 1,   currency: "USD", enabled: true,  description: "Netflix is the world's leading streaming entertainment service with 260M+ paid subscribers across 190 countries." },
  { id: "JPMC",  category: "stocks", name: "JPMorgan Chase & Co.",  symbol: "JPM",   icon: "J",  price: 198.45, change24h: 0.95,  changePct24h: 0.48,  marketCap: "$571B",  volume24h: "$8.1B",  exchange: "NYSE",    minInvestment: 1,   currency: "USD", enabled: true,  description: "JPMorgan Chase is the largest US bank by assets, offering investment banking, commercial banking, financial services and asset management." },

  // ─── ETFs ─────────────────────────────────────────────────────────────────
  { id: "SPY",   category: "etfs", name: "SPDR S&P 500 ETF",       symbol: "SPY",   icon: "S",  price: 521.30, change24h: 2.10,  changePct24h: 0.40,  marketCap: "$508B",  volume24h: "$28.4B", exchange: "NYSE",    minInvestment: 1,   currency: "USD", enabled: true,  description: "Tracks the S&P 500 index, providing exposure to 500 of the largest US companies. One of the world's most traded ETFs." },
  { id: "QQQ",   category: "etfs", name: "Invesco QQQ Trust",      symbol: "QQQ",   icon: "Q",  price: 439.55, change24h: 3.20,  changePct24h: 0.73,  marketCap: "$245B",  volume24h: "$19.8B", exchange: "NASDAQ",  minInvestment: 1,   currency: "USD", enabled: true,  description: "Tracks the NASDAQ-100 index, heavily weighted toward large-cap technology stocks. Popular for growth-oriented investors." },
  { id: "VTI",   category: "etfs", name: "Vanguard Total Market",  symbol: "VTI",   icon: "V",  price: 238.70, change24h: 1.05,  changePct24h: 0.44,  marketCap: "$380B",  volume24h: "$5.6B",  exchange: "NYSE",    minInvestment: 1,   currency: "USD", enabled: true,  description: "Provides exposure to the entire US stock market, covering large-, mid-, small- and micro-cap stocks. Ultra-low expense ratio." },
  { id: "VOO",   category: "etfs", name: "Vanguard S&P 500 ETF",   symbol: "VOO",   icon: "V",  price: 479.20, change24h: 1.95,  changePct24h: 0.41,  marketCap: "$436B",  volume24h: "$6.3B",  exchange: "NYSE",    minInvestment: 1,   currency: "USD", enabled: true,  description: "Vanguard's version of the S&P 500 ETF, known for its extremely low 0.03% expense ratio. Ideal for long-term investors." },
  { id: "ARKK",  category: "etfs", name: "ARK Innovation ETF",     symbol: "ARKK",  icon: "K",  price: 48.35,  change24h: -0.75, changePct24h: -1.53, marketCap: "$6.8B",  volume24h: "$1.2B",  exchange: "NYSE",    minInvestment: 1,   currency: "USD", enabled: true,  description: "Actively managed ETF focused on disruptive innovation including genomics, AI, fintech, autonomous tech and next-gen internet." },
  { id: "IWM",   category: "etfs", name: "iShares Russell 2000",   symbol: "IWM",   icon: "I",  price: 201.15, change24h: 0.60,  changePct24h: 0.30,  marketCap: "$62B",   volume24h: "$4.7B",  exchange: "NYSE",    minInvestment: 1,   currency: "USD", enabled: true,  description: "Tracks the Russell 2000 index of small-cap US stocks, offering exposure to the smaller end of the US equity market." },
  { id: "EEM",   category: "etfs", name: "iShares MSCI Emerging",  symbol: "EEM",   icon: "E",  price: 42.80,  change24h: 0.25,  changePct24h: 0.59,  marketCap: "$22B",   volume24h: "$1.5B",  exchange: "NYSE",    minInvestment: 1,   currency: "USD", enabled: true,  description: "Provides exposure to large and mid-cap equities from emerging market countries including China, India, Brazil, Taiwan and South Korea." },
  { id: "XLE",   category: "etfs", name: "Energy Select Sector",   symbol: "XLE",   icon: "E",  price: 89.45,  change24h: 1.20,  changePct24h: 1.36,  marketCap: "$38B",   volume24h: "$1.8B",  exchange: "NYSE",    minInvestment: 1,   currency: "USD", enabled: true,  description: "Tracks energy companies in the S&P 500, including oil, gas, consumable fuels and energy equipment & services companies." },
  { id: "GLDETF",category: "etfs", name: "SPDR Gold Shares ETF",   symbol: "GLD",   icon: "G",  price: 214.60, change24h: 0.80,  changePct24h: 0.37,  marketCap: "$64B",   volume24h: "$2.1B",  exchange: "NYSE",    minInvestment: 1,   currency: "USD", enabled: true,  description: "Backed by physical gold stored in vaults. Provides gold exposure without the complexity of storing physical metal." },
  { id: "SLVETF",category: "etfs", name: "iShares Silver Trust",   symbol: "SLV",   icon: "S",  price: 23.15,  change24h: 0.35,  changePct24h: 1.54,  marketCap: "$9.2B",  volume24h: "$0.8B",  exchange: "NYSE",    minInvestment: 1,   currency: "USD", enabled: true,  description: "Backed by physical silver, offering exposure to silver spot price performance through a simple ETF structure." },

  // ─── BONDS ────────────────────────────────────────────────────────────────
  { id: "US10Y",  category: "bonds", name: "US 10-Year Treasury",   symbol: "US10Y",  icon: "$",  price: 98.20,  change24h: 0.05,  changePct24h: 0.05,  marketCap: "—",     volume24h: "—",     exchange: "US Treasury", minInvestment: 100, currency: "USD", enabled: true,  yield: "4.52%", maturity: "10 Years", rating: "AAA", description: "Benchmark US government bond maturing in 10 years. Considered virtually risk-free and widely used as a global safe-haven asset." },
  { id: "US30Y",  category: "bonds", name: "US 30-Year Treasury",   symbol: "US30Y",  icon: "$",  price: 93.40,  change24h: -0.10, changePct24h: -0.11, marketCap: "—",     volume24h: "—",     exchange: "US Treasury", minInvestment: 100, currency: "USD", enabled: true,  yield: "4.75%", maturity: "30 Years", rating: "AAA", description: "Long-duration US government bond. Offers higher yield than the 10Y with greater sensitivity to interest rate changes." },
  { id: "US2Y",   category: "bonds", name: "US 2-Year Treasury",    symbol: "US2Y",   icon: "$",  price: 99.85,  change24h: 0.02,  changePct24h: 0.02,  marketCap: "—",     volume24h: "—",     exchange: "US Treasury", minInvestment: 100, currency: "USD", enabled: true,  yield: "4.90%", maturity: "2 Years",  rating: "AAA", description: "Short-term US government note. Highly liquid and sensitive to Fed policy decisions. Used as a proxy for near-term rate expectations." },
  { id: "UKGILT", category: "bonds", name: "UK 10Y Gilt",           symbol: "UKT10",  icon: "£",  price: 96.10,  change24h: -0.08, changePct24h: -0.08, marketCap: "—",     volume24h: "—",     exchange: "UK DMO",     minInvestment: 100, currency: "GBP", enabled: true,  yield: "4.28%", maturity: "10 Years", rating: "AA",  description: "UK government bond issued by the UK Debt Management Office. Considered very low risk and denominated in GBP." },
  { id: "BUND",   category: "bonds", name: "German 10Y Bund",       symbol: "DBR10",  icon: "€",  price: 97.65,  change24h: 0.03,  changePct24h: 0.03,  marketCap: "—",     volume24h: "—",     exchange: "Deutsche Finance", minInvestment: 100, currency: "EUR", enabled: true, yield: "2.50%", maturity: "10 Years", rating: "AAA", description: "German government bond — the euro area benchmark bond. Considered the safest EUR-denominated sovereign bond." },

  // ─── FIXED INCOME ─────────────────────────────────────────────────────────
  { id: "TBILL3M", category: "fixed_income", name: "US T-Bill 3-Month",      symbol: "TBILL3M", icon: "$",  price: 99.92,  change24h: 0.01,  changePct24h: 0.01,  marketCap: "—",     volume24h: "—",     exchange: "US Treasury", minInvestment: 100,  currency: "USD", enabled: true,  yield: "5.28%", maturity: "3 Months", rating: "AAA", description: "Short-term US government obligation with near-zero default risk. Popular cash management instrument for institutional investors." },
  { id: "IGBOND",  category: "fixed_income", name: "IG Corporate Bond",       symbol: "IGBOND",  icon: "IG", price: 97.30,  change24h: 0.10,  changePct24h: 0.10,  marketCap: "—",     volume24h: "—",     exchange: "OTC",         minInvestment: 500,  currency: "USD", enabled: true,  yield: "5.45%", maturity: "5 Years",  rating: "BBB", description: "Investment-grade corporate bond basket tracking debt from companies with strong credit ratings. Offers yield premium over Treasuries." },
  { id: "HYBOND",  category: "fixed_income", name: "High-Yield Corp Bond",    symbol: "HYBOND",  icon: "HY", price: 95.10,  change24h: -0.20, changePct24h: -0.21, marketCap: "—",     volume24h: "—",     exchange: "OTC",         minInvestment: 500,  currency: "USD", enabled: true,  yield: "7.80%", maturity: "5 Years",  rating: "BB",  description: "Below-investment-grade corporate bonds offering higher yields in exchange for greater credit risk. Also called junk bonds." },
  { id: "MUNI",    category: "fixed_income", name: "Municipal Bond",          symbol: "MUNI",    icon: "M",  price: 98.50,  change24h: 0.05,  changePct24h: 0.05,  marketCap: "—",     volume24h: "—",     exchange: "OTC",         minInvestment: 500,  currency: "USD", enabled: true,  yield: "3.80%", maturity: "10 Years", rating: "AA",  description: "Debt securities issued by US states and municipalities. Interest income is typically exempt from federal income tax." },
  { id: "AGMBS",   category: "fixed_income", name: "Agency MBS",              symbol: "AGMBS",   icon: "AG", price: 96.40,  change24h: 0.08,  changePct24h: 0.08,  marketCap: "—",     volume24h: "—",     exchange: "OTC",         minInvestment: 1000, currency: "USD", enabled: true,  yield: "5.65%", maturity: "30 Years", rating: "AAA", description: "Mortgage-backed securities guaranteed by Fannie Mae, Freddie Mac or Ginnie Mae. Offer higher yield than Treasuries with implicit government backing." },

  // ─── COMMODITIES ──────────────────────────────────────────────────────────
  { id: "WTICRUDE", category: "commodities", name: "WTI Crude Oil",    symbol: "WTI",     icon: "🛢",  price: 82.45,  change24h: 1.10,  changePct24h: 1.35,  marketCap: "—",     volume24h: "$22B",   exchange: "NYMEX",  minInvestment: 10,  currency: "USD", enabled: true,  unit: "per barrel", description: "West Texas Intermediate — the US benchmark crude oil. Price affected by OPEC decisions, US inventory levels and global demand trends." },
  { id: "NATGAS",   category: "commodities", name: "Natural Gas",      symbol: "NG",      icon: "🔥",  price: 1.95,   change24h: -0.05, changePct24h: -2.50, marketCap: "—",     volume24h: "$4.5B",  exchange: "NYMEX",  minInvestment: 10,  currency: "USD", enabled: true,  unit: "per MMBtu",  description: "Henry Hub natural gas — the North American benchmark for natural gas. Highly seasonal commodity driven by weather and LNG exports." },
  { id: "WHEAT",    category: "commodities", name: "Wheat",            symbol: "ZW",      icon: "🌾",  price: 545.25, change24h: 4.75,  changePct24h: 0.88,  marketCap: "—",     volume24h: "$1.2B",  exchange: "CBOT",   minInvestment: 10,  currency: "USD", enabled: true,  unit: "per bushel", description: "CBOT wheat futures — a global agricultural benchmark affected by weather, geopolitics and global food supply dynamics." },
  { id: "CORN",     category: "commodities", name: "Corn",             symbol: "ZC",      icon: "🌽",  price: 435.50, change24h: 2.25,  changePct24h: 0.52,  marketCap: "—",     volume24h: "$1.8B",  exchange: "CBOT",   minInvestment: 10,  currency: "USD", enabled: true,  unit: "per bushel", description: "CBOT corn futures. Primary uses include food, animal feed and ethanol production. Sensitive to US planting intentions and South American harvests." },
  { id: "COFFEE",   category: "commodities", name: "Coffee",           symbol: "KC",      icon: "☕",  price: 190.35, change24h: -1.20, changePct24h: -0.63, marketCap: "—",     volume24h: "$0.8B",  exchange: "ICE",    minInvestment: 10,  currency: "USD", enabled: true,  unit: "per lb",     description: "ICE Arabica coffee futures — affected by weather in Brazil and Colombia, currency fluctuations and global demand trends." },
  { id: "COTTON",   category: "commodities", name: "Cotton",           symbol: "CT",      icon: "🌿",  price: 79.85,  change24h: 0.55,  changePct24h: 0.69,  marketCap: "—",     volume24h: "$0.5B",  exchange: "ICE",    minInvestment: 10,  currency: "USD", enabled: true,  unit: "per lb",     description: "ICE cotton futures — a key input for textile industry. Price influenced by weather, global supply and trade policy." },
  { id: "SOYBEANS", category: "commodities", name: "Soybeans",         symbol: "ZS",      icon: "🫘",  price: 1132.5, change24h: 6.25,  changePct24h: 0.55,  marketCap: "—",     volume24h: "$2.2B",  exchange: "CBOT",   minInvestment: 10,  currency: "USD", enabled: true,  unit: "per bushel", description: "CBOT soybean futures. Used for crushing into soybean oil and meal for animal feed. Affected by South American weather and Chinese demand." },

  // ─── FUTURES ──────────────────────────────────────────────────────────────
  { id: "ES",       category: "futures", name: "S&P 500 E-Mini",      symbol: "ES",      icon: "ES", price: 5215.50, change24h: 18.25, changePct24h: 0.35,  marketCap: "—",     volume24h: "$280B",  exchange: "CME",    minInvestment: 50, currency: "USD", enabled: true,  expiryDate: "Jun 2025", contractSize: "$50×index", description: "The most liquid equity index futures contract in the world. Used for hedging S&P 500 exposure and speculative trading." },
  { id: "NQ",       category: "futures", name: "NASDAQ E-Mini",       symbol: "NQ",      icon: "NQ", price: 18440.25,change24h: 95.50, changePct24h: 0.52,  marketCap: "—",     volume24h: "$180B",  exchange: "CME",    minInvestment: 50, currency: "USD", enabled: true,  expiryDate: "Jun 2025", contractSize: "$20×index", description: "E-mini futures tracking the NASDAQ-100 index. Popular with tech sector traders and hedge funds." },
  { id: "CL",       category: "futures", name: "Crude Oil Futures",   symbol: "CL",      icon: "CL", price: 82.80,   change24h: 1.15,  changePct24h: 1.41,  marketCap: "—",     volume24h: "$45B",   exchange: "NYMEX",  minInvestment: 50, currency: "USD", enabled: true,  expiryDate: "May 2025", contractSize: "1,000 bbl", description: "WTI crude oil futures — the benchmark for US oil pricing. Highly liquid with massive daily volumes from traders, hedgers and producers." },
  { id: "GCF",      category: "futures", name: "Gold Futures",        symbol: "GC",      icon: "GC", price: 2315.80, change24h: 12.40, changePct24h: 0.54,  marketCap: "—",     volume24h: "$35B",   exchange: "COMEX",  minInvestment: 50, currency: "USD", enabled: true,  expiryDate: "Jun 2025", contractSize: "100 troy oz", description: "COMEX gold futures — used for hedging inflation risk and geopolitical uncertainty. One of the oldest futures markets globally." },
  { id: "SIF",      category: "futures", name: "Silver Futures",      symbol: "SI",      icon: "SI", price: 27.45,   change24h: 0.38,  changePct24h: 1.40,  marketCap: "—",     volume24h: "$8B",    exchange: "COMEX",  minInvestment: 50, currency: "USD", enabled: true,  expiryDate: "May 2025", contractSize: "5,000 troy oz", description: "COMEX silver futures — more volatile than gold with significant industrial demand. Used for speculation and industrial hedging." },
  { id: "NGF",      category: "futures", name: "Natural Gas Futures",  symbol: "NGF",     icon: "NG", price: 1.98,    change24h: -0.04, changePct24h: -1.98, marketCap: "—",     volume24h: "$6B",    exchange: "NYMEX",  minInvestment: 50, currency: "USD", enabled: true,  expiryDate: "May 2025", contractSize: "10,000 MMBtu", description: "Henry Hub natural gas futures. Among the most volatile commodity futures due to weather seasonality and rapidly shifting supply/demand." },

  // ─── OPTIONS ──────────────────────────────────────────────────────────────
  { id: "AAPL-CALL-200", category: "options", name: "AAPL Call $200",   symbol: "AAPL $200C", icon: "C", price: 4.80,  change24h: 0.35,  changePct24h: 7.87,  marketCap: "—", volume24h: "—", exchange: "CBOE", minInvestment: 10, currency: "USD", enabled: true,  optionType: "Call", strike: "$200", expiry: "Jun 20, 2025", underlying: "AAPL", description: "Call option on Apple stock with $200 strike. Profitable if AAPL rises above $200 before expiry. Leverage amplifies both gains and losses." },
  { id: "SPY-PUT-500",   category: "options", name: "SPY Put $500",     symbol: "SPY $500P",  icon: "P", price: 8.25,  change24h: -0.50, changePct24h: -5.71, marketCap: "—", volume24h: "—", exchange: "CBOE", minInvestment: 10, currency: "USD", enabled: true,  optionType: "Put",  strike: "$500", expiry: "Jun 20, 2025", underlying: "SPY",  description: "Put option on SPY ETF with $500 strike. Provides downside protection or speculative short exposure to S&P 500." },
  { id: "TSLA-CALL-200", category: "options", name: "TSLA Call $200",   symbol: "TSLA $200C", icon: "C", price: 6.15,  change24h: -0.80, changePct24h: -11.5, marketCap: "—", volume24h: "—", exchange: "CBOE", minInvestment: 10, currency: "USD", enabled: true,  optionType: "Call", strike: "$200", expiry: "Jun 20, 2025", underlying: "TSLA", description: "Call option on Tesla stock. High implied volatility makes Tesla options expensive but potentially very rewarding if the stock moves sharply." },
  { id: "NVDA-CALL-900", category: "options", name: "NVDA Call $900",   symbol: "NVDA $900C", icon: "C", price: 22.50, change24h: 3.10,  changePct24h: 15.97, marketCap: "—", volume24h: "—", exchange: "CBOE", minInvestment: 10, currency: "USD", enabled: true,  optionType: "Call", strike: "$900", expiry: "Jun 20, 2025", underlying: "NVDA", description: "Call option on NVIDIA stock. AI demand narrative makes NVDA one of the most actively traded options contracts in the market." },
  { id: "QQQ-PUT-420",   category: "options", name: "QQQ Put $420",     symbol: "QQQ $420P",  icon: "P", price: 5.40,  change24h: 0.20,  changePct24h: 3.85,  marketCap: "—", volume24h: "—", exchange: "CBOE", minInvestment: 10, currency: "USD", enabled: true,  optionType: "Put",  strike: "$420", expiry: "Jun 20, 2025", underlying: "QQQ",  description: "Put option on QQQ ETF providing bearish exposure to NASDAQ-100 technology stocks. Popular hedge for tech-heavy portfolios." },

  // ─── METALS ───────────────────────────────────────────────────────────────
  { id: "XAUUSD", category: "metals", name: "Gold Spot",       symbol: "XAU/USD", icon: "Au", price: 2318.50, change24h: 14.20, changePct24h: 0.62,  marketCap: "~$14T", volume24h: "$220B", exchange: "OTC Spot", minInvestment: 10, currency: "USD", enabled: true,  unit: "per troy oz", description: "Gold spot price — the world's premier safe-haven asset. Inversely correlated with USD and real interest rates. Central bank favorite reserve." },
  { id: "XAGUSD", category: "metals", name: "Silver Spot",     symbol: "XAG/USD", icon: "Ag", price: 27.55,   change24h: 0.42,  changePct24h: 1.55,  marketCap: "~$1.7T",volume24h: "$15B",  exchange: "OTC Spot", minInvestment: 10, currency: "USD", enabled: true,  unit: "per troy oz", description: "Silver spot price — dual role as precious metal and industrial commodity (solar panels, electronics). More volatile than gold." },
  { id: "XPTUSD", category: "metals", name: "Platinum Spot",   symbol: "XPT/USD", icon: "Pt", price: 985.30,  change24h: 8.15,  changePct24h: 0.84,  marketCap: "~$230B",volume24h: "$1.2B", exchange: "OTC Spot", minInvestment: 10, currency: "USD", enabled: true,  unit: "per troy oz", description: "Platinum spot price — rarer than gold with significant auto-catalyst demand (catalytic converters). Strong South African supply concentration." },
  { id: "XPDUSD", category: "metals", name: "Palladium Spot",  symbol: "XPD/USD", icon: "Pd", price: 1045.80, change24h: -5.60, changePct24h: -0.53, marketCap: "~$80B", volume24h: "$0.5B", exchange: "OTC Spot", minInvestment: 10, currency: "USD", enabled: true,  unit: "per troy oz", description: "Palladium — used primarily in catalytic converters for petrol engines. One of the rarest metals with most supply from Russia and South Africa." },
  { id: "XCUUSD", category: "metals", name: "Copper Spot",     symbol: "XCU/USD", icon: "Cu", price: 4.28,    change24h: 0.06,  changePct24h: 1.42,  marketCap: "~$800B",volume24h: "$12B",  exchange: "LME",      minInvestment: 10, currency: "USD", enabled: true,  unit: "per lb",      description: "Copper — the 'PhD in economics' metal. Critical for electrification, EV batteries and renewable energy infrastructure. A key indicator of global growth." },

  // ─── NFTs ─────────────────────────────────────────────────────────────────
  { id: "PUNKS",   category: "nfts", name: "CryptoPunks",         symbol: "PUNKS",  icon: "👾", price: 48500,  change24h: 850,   changePct24h: 1.79,  marketCap: "$1.5B", volume24h: "$3.2M", exchange: "Ethereum", minInvestment: 100, currency: "USD", enabled: true,  blockchain: "Ethereum", supply: "10,000", floorPrice: "48.5 ETH", description: "CryptoPunks — one of the first NFT projects on Ethereum. 10,000 algorithmically generated pixel art characters. Iconic status as OG NFT collection." },
  { id: "BAYC",    category: "nfts", name: "Bored Ape Yacht Club",symbol: "BAYC",   icon: "🦍", price: 32500,  change24h: -500,  changePct24h: -1.52, marketCap: "$1.2B", volume24h: "$1.8M", exchange: "Ethereum", minInvestment: 100, currency: "USD", enabled: true,  blockchain: "Ethereum", supply: "10,000", floorPrice: "32.5 ETH", description: "Bored Ape Yacht Club — collection of 10,000 unique Bored Ape NFTs. Holder membership grants access to exclusive events and commercial rights to the ape." },
  { id: "AZUKI",   category: "nfts", name: "Azuki",               symbol: "AZUKI",  icon: "🎴", price: 8900,   change24h: 120,   changePct24h: 1.37,  marketCap: "$220B", volume24h: "$0.9M", exchange: "Ethereum", minInvestment: 100, currency: "USD", enabled: true,  blockchain: "Ethereum", supply: "10,000", floorPrice: "8.9 ETH",  description: "Azuki is a brand for the metaverse — built by anime and streetwear enthusiasts. High-quality art with a strong community and brand partnerships." },
  { id: "DOODLES", category: "nfts", name: "Doodles",             symbol: "DOODLE", icon: "🌈", price: 4200,   change24h: 85,    changePct24h: 2.07,  marketCap: "$105B", volume24h: "$0.5M", exchange: "Ethereum", minInvestment: 100, currency: "USD", enabled: true,  blockchain: "Ethereum", supply: "10,000", floorPrice: "4.2 ETH",  description: "Doodles is a community-driven NFT collection featuring colorful and unique characters. Known for active community governance and events." },
  { id: "CLONEX",  category: "nfts", name: "Clone X",             symbol: "CLONEX", icon: "🤖", price: 3800,   change24h: -120,  changePct24h: -3.07, marketCap: "$95B",  volume24h: "$0.6M", exchange: "Ethereum", minInvestment: 100, currency: "USD", enabled: true,  blockchain: "Ethereum", supply: "19,000", floorPrice: "3.8 ETH",  description: "Clone X by RTFKT x Takashi Murakami — 3D avatar collection designed for the metaverse. Each clone can be used in games and virtual worlds." },
];

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────
export const getCategoryById = (id) =>
  INVESTMENT_CATEGORIES.find((c) => c.id === id) ?? null;

export const getInstrumentById = (id) =>
  INVESTMENT_INSTRUMENTS.find((i) => i.id === id) ?? null;

export const getInstrumentsByCategory = (categoryId) =>
  INVESTMENT_INSTRUMENTS.filter((i) => i.category === categoryId);

// Merge static catalog with admin overrides from platform_settings
// overrides shape: { [instrumentId]: { price?, change24h?, changePct24h?, enabled?, minInvestment?, customInstruments?: [] } }
export const mergeWithOverrides = (overrides = {}) => {
  const base = [...INVESTMENT_INSTRUMENTS];

  // Apply per-instrument overrides
  const merged = base.map((inst) => {
    const ov = overrides[inst.id];
    if (!ov) return inst;
    return { ...inst, ...ov };
  });

  // Append any admin-added custom instruments
  const custom = overrides.__custom ?? [];
  return [...merged, ...custom];
};
